### ISSUE TITLE
camelCase vs PascalCase for string enumerations

### ISSUE THREAD

**Issue by greenmooseSE** [Microsoft/api-guidelines#100]
In documentation at https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#710-response-formats we can see
...
Property | Type | Required | Description
-- | -- | -- | --
code | String (enumerated) | ✔ | One of a server-defined set of error codes.
...
```csharp
{
  "error": {
    "code": "BadArgument",
    "message": "Previous passwords may not be reused",
    "target": "password",
    "innererror": {
      "code": "PasswordError",
      "innererror": {
        "code": "PasswordDoesNotMeetPolicy",
        "minLength": "6",
        "maxLength": "64",
        "characterTypes": ["lowerCase","upperCase","number","symbol"],
        "minDistinctCharacterTypes": "2",
        "innererror": {
          "code": "PasswordReuseNotAllowed"
        }
      }
    }
  }
}
```
Here property `code` is PascalCase'd as "BadArgument". and property `characterTypes` as camelCase'd.

This seems a bit confusing, since `characterTypes` seems to be enumeration of some sort, so why do they use camelCase but `code` use PascalCase?

Is there a guideline from Microsoft what casing enumerated string values should have? Is it PascalCase that is recommended?

Thanks.

**Comment by gareth-a-jones** [comment]
Enumerations are lowerCamelCase.

Yeah, this is unfortunate.  It should NOT say "string(enumerated)" .  It is ether an enumerated type or a string.  There is no such thing as an enumerated string.   Code is a string, which come from aggregations of errors codes across all levels of errors, some of which might look like enumerated value sets and some not.   characterTypes was just some example data.

**Comment by gareth-a-jones** [comment]
Thanks for the PR Julie.  I'm wondering if '(from a fixed set)' would actually capture the intent better than just removing it totally?
