### ISSUE TITLE
Question: Proper responds status code from API

### ISSUE THREAD

**Issue by rachyliu** [Microsoft/api-guidelines#102]
Hello,

Our team is debating what status code should the API return when the UI sends a request and the API finds no match (empty response). For example:

An existing user do not have anything in his/her shopping cart. The user id is 1234 and UI makes a call to the API (.../api/getcartitem/1234) to get the cart items for this user. Since the user do not have anything in the shopping cart, what status code should this call returns in the response? 

From the JavaScript perspective, I am used to handle 404 as an error and not an empty response. From the API developer perspective, 404 is just a status code and since no items were found with this user id, they are returning 404. 

Please let us know how should we understand this and the recommended practice. Thank you!

**Comment by darrelmiller** [comment]
I wouldn't recommend using 404 to indicate an empty shopping cart.  If there is an explicit process to create a cart and delete a cart then a 404 would indicate the need to create a cart.  A client that requests to see the contents of the cart when the cart is empty, is not a "client error".  At least that is quite a stretch.

Assuming that carts are implicitly created when you add items to them, there are two options for indicating an empty cart.  You can return a 200 and a empty object/array, or return a 204 that has no response body at all.

**Comment by zaverden** [comment]
See here: https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#51-errors

4xx indicates that client has sent an invalid request (wrong path, bad format, unsupported method, etc.). And if I get you description right, then empty card is not a problem, it is a valid state of application => 404 does not suet here.

200 vs 204 is like empty array vs null. Decision here depends on you style and preferences. 
Personally, I prefer to have 200 and be sure that I always receive array (empty or not) in a response body.
