### ISSUE TITLE
Put the Guidelines.md into the Readme.md

### ISSUE THREAD

**Issue by ckuijjer** [Microsoft/api-guidelines#105]
It's a minor issue, but when I search the web for _microsoft rest api guidelines_ I end up in the github repository and I'll have to manually click on the `Guidelines.md` to start reading. I think it's a nice idea to simply put the content of the guidelines into the `README.md`.

**Comment by mgefimov** [comment]
+1

**Comment by AndrewCraswell** [comment]
+1

**Comment by TomasHubelbauer** [comment]
This would be a really nice improvements and one of the PRs is even approved, although that is from fours months ago and since then there have presumably been more changes. Hopefully it gets updated and merged at some point.

**Comment by TomasHubelbauer** [comment]
A good suggestion by @tomkerkhove in #178 relating to preserving existing links:

> Concerning breaking linkes - That can easily be fixed by keeping the file with a pointer to new location.

Just keep `GUIDELINES.md`, delete content, keep only headers and underneath each header provide a link to the README or to the actual GitHub Pages site as per #178.

**Comment by gareth-a-jones** [comment]
Thanks for the feedback and the votes but we've decided not to accept this suggestion.  We feel like the two files serve different purposes and allow us to add separate extra guidelines in future is we so choose.
