### ISSUE TITLE
Problem with BluetoothLE code, GattCommunicationStatus.Success is not working

### ISSUE THREAD

**Issue by shikhartandon1993** [Microsoft/api-guidelines#108]
Hi
I am using a code named "BluetoothLE" from https://github.com/Microsoft/Windows-universal-samples
In that UWP it enumerates perfectly but when I press Connect button it says "Device Unreachable".
the GattCommunicationStatus.Success method is not returning true value.
Thanks

**Comment by gareth-a-jones** [comment]
Shikhar, this is unfurtunately not relevant to this repo - did you perhaps mean to submit it in a different one?
