### ISSUE TITLE
NotFound vs. NotAuthorized

### ISSUE THREAD

**Issue by shazqadeer** [Microsoft/api-guidelines#109]
The Azure Blockchain team is building a service with get endpoints for retrieving objects associated with ids.  Such an endpoint could fail to return a result either if the supplied id does not exist or it exists but the user is not authorized to access the object at that id.  What is the recommendation for the appropriate error code to be returned: NotFound or NotAuthorized?

**Comment by gareth-a-jones** [comment]
Confusingly, given its name, I believe the notAuthorized code should really only be used for AUTHN errors.  i.e. your token is incorrect in some major way.

AUTHZ errors should be opaque, so your ID space can't be fished by a low-privilege user to find an attack surface, so I would recommend just a 404 either way.

**Comment by daspek** [comment]
I'm actually a fan of the reverse -- default to AccessDenied.
Caller is authorized to interrogate this namespace and the item does not exist --> NotFound
Caller does not have permission but the item DOES exist --> AccessDenied
Caller does not have permission but the item DOES NOT exist --> AccessDenied (you can't interrogate the namespace)

in my experience, the problem with NotFound is that if a permission bug creeps up, apps can't tell the difference between "this got deleted on the server; let me delete my private copy, too" and "I have a bug and can't talk to the server properly anymore."

**Comment by gareth-a-jones** [comment]
That's fair - just so long as it's the same error either way when the caller does not have permission.

**Comment by darrelmiller** [comment]
@daspek Am I correct in assuming by AccessDenied, you mean 403?

I also like the approach you outline, but it does require implementation frameworks to support being able to check permissions for a URI space as opposed to a specific resource.  Sometimes that's easy, sometimes it is less easy.

**Comment by tomkerkhove** [comment]
Probably a stupid question but how do you distinguish the 403 for the supplier id to which he does not have access or the API in general? Do you provide some context somewhere?

**Comment by darrelmiller** [comment]
@tomkerkhove I think you would need to invent some payload format to identify what permissions are missing.  I don't think there is anything standard.

**Comment by gareth-a-jones** [comment]
So I think we settled on Daron's guidance here - use AccessDenied for all cases where you aren't authorized.
