### ISSUE TITLE
RFC 2616 is obsolete

### ISSUE THREAD

**Issue by dret** [Microsoft/api-guidelines#12]
as https://tools.ietf.org/html/rfc2616 shows, RFC 2616 has been obsoleted by a set of newer RFCs a while ago. @mnot has an excellent post about this at https://www.mnot.net/blog/2014/06/07/rfc2616_is_dead, which is already 2 years old. it will not be trivial to remove all RFC 2616 references from the guidelines, but it should be done better sooner than later since HTTP is such a central piece.

**Comment by darrelmiller** [comment]
@dret Beat you to it #6  ;-)

**Comment by dret** [comment]
On 2016-07-19 22:56, Darrel wrote:
> @dret <https://github.com/dret> Beat you to it #6

oops. you're fast, @darrelmiller. closing this one as a duplicate of #6.
