### ISSUE TITLE
Consideration: Breaking standards into separate markdown files?

### ISSUE THREAD

**Issue by imajes** [Microsoft/api-guidelines#15]
The standards are long and extensive, covering many areas of an API. Is there any consideration worth making to split into multiple files, perhaps one per chapter? Especially since you can use build tools to combine + publish a final spec file. This may make it easier to manage the document in the longer term.

**Comment by RobDolinMS** [comment]
Thanks @imajes.  There were definitely multiple perspectives on this as we prepared to publish the guidelines.  Some folks felt we should break-down the single Guidelines.md file into multiple files for some of the reasons you state above.  Others preferred the simplicity of a single file (with hyperlinked index) as it eliminates the requirement of any tooling to combine + publish; and it makes reviews of changes across multiple "chapters" easy to review as a single file.

**Comment by cleemullins** [comment]
This is certainly something I think we'll consider in the future.
