### ISSUE TITLE
Section 8.2 of Guidelines.md: JSON-P linked website is actually a parked domain

### ISSUE THREAD

**Issue by francescorw** [Microsoft/api-guidelines#17]
The referenced website http://www.json-p.org/ hosts the classic "domain for sale" page.

**Comment by francescorw** [comment]
Whoops, closed due to already existing pull request https://github.com/Microsoft/api-guidelines/pull/16

**Comment by RobDolinMS** [comment]
Thanks for opening the issue @francescorw and thanks for cleaning it up too :)
