### ISSUE TITLE
Question: What is the significance of "$" in $filter, $order etc

### ISSUE THREAD

**Issue by ghost** [Microsoft/api-guidelines#173]
A basic, but honest question: What is the significance of the "$" in $filter, $top, $order query parameters? Is there a different interpretation for query parameters that do not contain this prefix?

**Comment by gareth-a-jones** [comment]
It's just an older convention that we picked up from OData.  We are gradually moving to accept both with and without.

Certainly you should not differentiate in meaning between parameters named $foo and foo as that would confuse users terribly.
