### ISSUE TITLE
Section 9.7.3 format Error

### ISSUE THREAD

**Issue by SMAH1** [Microsoft/api-guidelines#176]
In section `9.7.3 Operator precedence` text not formatted correctly.
After `Relational` in table, show mistake.
I saw raw format is correct but README.md show not correct.

![Untitled](https://user-images.githubusercontent.com/21136680/55709767-4a9ed800-59fe-11e9-89af-398f82bbfa08.png)

**Comment by brian-vosburgh** [comment]
This can be fixed by prefixing each line in the table with another pipe.
