### ISSUE TITLE
How should recordset count be returned?

### ISSUE THREAD

**Issue by jaredmoo** [Microsoft/api-guidelines#177]
https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#983-additional-considerations

> Recordset count: Developers who want to know the full number of records across all pages, MAY include the query parameter $count=true to tell the server to include the count of items in the response.

How exactly should the count be returned? I assume it should be an additional value in the collection like this:

```
GET http://api.contoso.com/v1.0/people HTTP/1.1
Accept: application/json

HTTP/1.1 200 OK
Content-Type: application/json

{
  ...,
  "value": [...],
  "nextLink": "{opaqueUrl}"
  "count": 1234
}
```

**Comment by gareth-a-jones** [comment]
That's correct, or if you happen to be using OData as your implementation it is an annotation @odata.count or @count.
