### ISSUE TITLE
Question: What tool do you use to draw Sequence diagram?

### ISSUE THREAD

**Issue by TranNgocKhoa** [Microsoft/api-guidelines#179]
I'm just wondering what tool do you use to draw the diagram. I like it and I'd like to use it :D

**Comment by cleemullins** [comment]
I use [WebSequenceDiagrams](https://www.websequencediagrams.com/). 

For my use, I just bought a license so I can use some of the extra features. Their free tier works quite well. One the things I like about it is that capturing the text (in a doc, in a github file, etc) gives you the full diagram. This makes it easier to track/modify/share than sending around binary files such as Visio diagrams.

**Comment by TranNgocKhoa** [comment]
Oh, thank you so much!
