### ISSUE TITLE
Translate guidelines to another language

### ISSUE THREAD

**Issue by mpetrinidev** [Microsoft/api-guidelines#181]
Is it possible to translate guidelines to multiple languages?
I'd like to collaborate with spanish.

**Comment by Paul-Dempsey** [comment]
Certainly you can. The Edge Dev browser I use has a right-click menu item to Translate the page. Even when it says "Translate to English", I can pick that and then choose another language where I can choose Spanish (may require adding it in settings). Although, I'm guessing that you really meant is to request that the guidelines be professionally translated into the world's languages for you and hosted here. That is expensive, and work to maintain. Perhaps the team will welcome volunteers to contribute translated versions.

**Comment by gareth-a-jones** [comment]
Mauro, the target of these guidelines is PRIMARILY Microsoft internal developers.    We publish them so the community can gain benefit and give us feedback.

As such, we don't have plans to translate the guidelines ourselves, as our worldwide developer cohort speaks English well enough to get the main benefit from them.

If you wanted to get together people to maintain translated mirror forks, then we'd be happy to give it some publicity.
