### ISSUE TITLE
Looking for guidelines - should one API always return the same "kind" of responses?

### ISSUE THREAD

**Issue by chuxia15** [Microsoft/api-guidelines#183]
Say we have an existing API to get a book object:
**GET api/books/{id}**

To call this API, you have to **include authentication token** as a HEADER in your request.
and the book object includes properties such as:
- Title
- Author
- Comments
- Publisher
...

Now we want to add some way for client to get some book info **without authentication**. And the the response for such request will include a subset of properties of the book object mentioned above, for example, only 2:
- Title
- Author

I have two questions:
1) In this case, should I have a separate API, and return a different entity (even though this entity is a subset of an existing one), OR should I use the same API?
2) If I use the same API, I'll need to somehow return different things depends on if there's authentication token present. In this case, I prefer to not include property like comments and author in my response when people send request without proper authentication, because in my opinion they don't suppose to know we have such information about the book. Then the question becomes - is it ok for one API to return different looking JSON objects depends on whether or not the request has a header?

**Comment by gareth-a-jones** [comment]
Personally I think it's fine if you wish to have a subset.      If the unauthenticated book had an actually different shape, then I think I would lean towards a different endpoint, but web purists would probably point more towards content negotiation and just having the content type be different.   However, with JSON formats, individualized content types for each chunk of JSON have often fallen by the wayside.  Your example illustrates why this is a shame.
