### ISSUE TITLE
Add Problem Details for HTTP APIs Error Reporting

### ISSUE THREAD

**Issue by euclid47** [Microsoft/api-guidelines#189]
I would like to suggest adding Problem Details, [RFC 7807](https://www.rfc-editor.org/rfc/rfc7807.txt), to the document.

**Comment by gareth-a-jones** [comment]
Hi eulid,
If 7807 had been around when we were standardizing the way we did errors at MSFT, then I'd agree.
At this time, the value of changing from our approach to 7807 or a compliant variant doesn't supersede the cost to customers of change and variance, so I'm going to reject this.

For those taking these guidelines and making their own, then I think it would be well worth a good, long look.
