### ISSUE TITLE
white space in url

### ISSUE THREAD

**Issue by copdips** [Microsoft/api-guidelines#194]
Hello,

I found the example given by [9.6. Sorting collections](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#96-sorting-collections) is using some white spaces, is it a best practice ?

> The expression MAY include the suffix "asc" for ascending or "desc" for descending, separated from the property name by one or more spaces.

`GET https://api.contoso.com/v1.0/people?$orderBy=name desc`

**Comment by gareth-a-jones** [comment]
In execution the url woudl be encoded to %20, but we choose to avoid encoding in the docuemnt for readability.

**Comment by copdips** [comment]
@garethj-msft 
yes I know white space is encoded to %20, and it works. My question is whether it is a best practice to use white space in URL if we have other choices? Why you chose white space instead of other solutions (+, &, etc.)

**Comment by gareth-a-jones** [comment]
I think it is a little questionable, but we were trying to stick with the OData standard which uses it, so we didn't have much choice.   If I were inventing a query syntax I would probably not use the spaces personally.

**Comment by copdips** [comment]
thx for your reply
