### ISSUE TITLE
With the UI overhaul for FancyZones in version 0.31.1 of PowerToys, #4098 is complete. The new editor looks great! Super grateful for all of the hard work going into these features!

### ISSUE THREAD

**Issue by Flyboy95** [Microsoft/api-guidelines#225]
With the UI overhaul for FancyZones in version 0.31.1 of PowerToys, #4098 is complete. The new editor looks great! Super grateful for all of the hard work going into these features!

_Originally posted by @JaimeStill in https://github.com/microsoft/PowerToys/issues/6611#issuecomment-772160069_

**Comment by gareth-a-jones** [comment]
Think you hit the wrong repo there Flyboy :-)

**Comment by nschonni** [comment]
@garethj-msft it's a bot
