### ISSUE TITLE
7.4.4 Link header example value is incorrect

### ISSUE THREAD

**Issue by avoidwork** [Microsoft/api-guidelines#23]
Hi,

The `Link` header value is defined as `"<" URI-Reference ">" *( ";" link-param )` by rfc5988, the current value form uses `{help}` instead of `</help>`. I assume the URI for `help` is meant to be relative to root, as defined by https://tools.ietf.org/html/rfc3987#section-3.1

Is the following:
```
Link: {help}; rel="help"
```

Probably should be:
```
Link: </help>; rel="help"
```

Including a link to the IANA reference might be useful for people getting started with correct hypermedia links: http://www.iana.org/assignments/link-relations/link-relations.xhtml

Cheers

**Comment by darrelmiller** [comment]
@avoidwork The guidelines seem to use `{help}` as a kind of URL parameter that is supposed to be replaced by the actual URL.  So I believe what the spec should say is,

`Link: <{help}>; rel="help"`

**Comment by avoidwork** [comment]
👍 if it's a place holder that makes sense to me.

**Comment by cleemullins** [comment]
The PR from @darrelmiller that's been merged resolves this.
