### ISSUE TITLE
URL patterns for collections should be covered elsewhere.  If not we'll need to cover them here.

### ISSUE THREAD

**Issue by markweitzel** [Microsoft/api-guidelines#245]
URL patterns for collections should be covered elsewhere.  If not we'll need to cover them here.

_Originally posted by @mkistler in https://github.com/microsoft/api-guidelines/pull/243#discussion_r653706954_

**Comment by mikekistler** [comment]
I think this is now covered in the latest version in the `azureRestUpdates` branch [here](https://github.com/microsoft/api-guidelines/blob/azureRestUpdates/azure/Guidelines.md#urls).

In particular, I added a description of the `resource-collection` and `resource-id` path segments, which I think is mostly what is needed.

**Comment by mikekistler** [comment]
Closing as it seems this has been addressed in the guidelines that were merged in #277.

We can reopen or create a new issue if necessary.
