### ISSUE TITLE
Azure Guidelines: Reconcile new guidelines with ARM recommendations

### ISSUE THREAD

**Issue by markweitzel** [Microsoft/api-guidelines#259]
Management plane implementations also have a specific set of recommendations and guidance. We need to ensure we are consistent across the board or that when we differ, we clearly communicate the reason & motivation for doing so.
See: [ARM API Review best-practices & common issues](https://armwiki.azurewebsites.net/rp_onboarding/process/api_review_best_practices.html)
<sub>Note: This is an internal MS site</sub>

**Comment by mikekistler** [comment]
Closing in favor of #273.  I'm using the newer issue rather than this one because it already contains some discussion and results.
