### ISSUE TITLE
Accept: being optional

### ISSUE THREAD

**Issue by decoderwheel** [Microsoft/api-guidelines#27]
Which HTTP guidelines specify that the content-types preferred by the client in the Accept: header are optional? I can't find anything to support that assertion. The header itself is optional, but as far as I know the server should either comply with the client's request, or return 406 Not Acceptable.

**Comment by bbarry** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1

> If no Accept header field is present, then it is assumed that the client accepts all media types. If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response.

**Comment by decoderwheel** [comment]
@bbarry Yes, that's what I said. However, the REST guidelines say (my emphasis):

> *Per the HTTP guidelines*, this is just a hint and responses MAY have a different content type,
> such as a blob fetch where a successful response will just be the blob stream as the payload.

However, I've just answered my own question; RFC2616 was obsoleted by RFC 7231 (amongst others), which now says this in Section 5.3.2:

> If the header field is present in a request and none of the available representations for the 
> response have a media type that is listed as acceptable, the origin server can either honor the 
> header field by sending a 406 (Not Acceptable) response or *disregard the header field by 
> treating the response as if it is not subject to content negotiation.*

I'd argue that's bad practice, but it is part of the spec.
