### ISSUE TITLE
Create guidelines on acronym casing in query params & JSON 

### ISSUE THREAD

**Issue by JeffreyRichter** [Microsoft/api-guidelines#280]
I think we should define guidelines for acronym casing to increase consistency across Azure services.  This came up because Go's acronym guidelines are that acronyms are all uppercase (Ex: HTTP) while .NET's is all uppercase for 2-letters  and mixed case for 3+ letters. It would be nice if there was a casing guideline for HTTP customers and it made it easy for code generators to do the right thing for their respective language.

**Comment by mikekistler** [comment]
I think we should not uppercase acronyms in the API definitions. We should use standard Pascal case for Schema names and camel case for property and parameter names.  (This last part is already clearly stated in the guidelines).

Languages that want acronyms to be upper-cased or some special casing can implement that in their generators. BTW Swift also wants common acronyms to be all upper-cased. 

I think using standard casing in the API definition makes it easier for languages that use standard casing -- that is, it's straightforward to convert camel-case to snake case.  But through in upper-cased acronyms and it gets a lot harder.

**Comment by JeffreyRichter** [comment]
I can agree with this. I do think we should have an explicit guideline bullet that explicitly states that acronyms should be pascal cased. If we don't some will do it one way and will do it another way.

**Comment by mikekistler** [comment]
Fixed in 7db5a22.
