### ISSUE TITLE
Address dangling PR comments on LRO Guidelines

### ISSUE THREAD

**Issue by mikekistler** [Microsoft/api-guidelines#289]
@tg-msft left a few comments on the LRO Guidelines that we did not get to address before merging.  We should address these in a follow-on PR:

![image](https://user-images.githubusercontent.com/85643503/133319320-2b91d83f-ad49-41c8-9ace-af9ec1c4e2b8.png)

**Comment by markweitzel** [comment]
Addressed as part of #353
