### ISSUE TITLE
DELETE entries in Optimistic Concurrency table should probably be If-Match

### ISSUE THREAD

**Issue by briancr-ms** [Microsoft/api-guidelines#290]
In the table in the Optimistic Concurrency section (https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#optimistic-concurrency), should the header for the DELETE entries be If-Match (not If-None-Match)?

If-Match is commonly used on state changing methods, like DELETE.

For DELETE, If-Match: "xyz" should return 412 if the value on the server does not match the value provided.
For DELETE, If-Match: "xyz" should return 204 if the value on the server matches the value provided.
For DELETE, If-Match: * should return 204 regardless of the value on the server.

**Comment by mikekistler** [comment]
That sounds right to me.  If none match, then I'm not sure what we'd be asking to delete.
