### ISSUE TITLE
Update & revise Long Running Operation guidance

### ISSUE THREAD

**Issue by markweitzel** [Microsoft/api-guidelines#319]
Over the past several weeks, there have been a number of issues that have come up around our current LRO guidance. This is the parent issue for revisiting and updating our recommendations in a more holistic manner.

### Related Issues
#289 
[`api-version` in the `Operation-Location` header for LROs]
(https://microsoft.sharepoint.com/:o:/t/AzureAPIStewardshipBoard/EoBZoCVHn2ZAsBHj3io3ZekBiyQLEsQ0Kvo738ehjrrUOw?e=N8W1HZ)

**Comment by JeffreyRichter** [comment]
Mike, will you be scheduling a meeting with all of us to kick this off?

**Comment by mikekistler** [comment]
@haocornell-ms FYI

**Comment by markweitzel** [comment]
Incorporated as part of #317
