### ISSUE TITLE
Add guidance on patching polymorphic types

### ISSUE THREAD

**Issue by mikekistler** [Microsoft/api-guidelines#331]
Add guidance on how to patch a polymorphic type (it is a bit tricky).

Clipped from email stream:

@bexxx says:

We discussed to change the ScaleSettings type of a deployment from a flat type to one using polymorphism to be future proof (in case we add a second type like “TrafficBased”…) and use the ScaleType as the type discriminator.
I did the changes and for GET and POST it looks ok.
 
Now we also have a PATCH with content-type Application/merge-patch+json. Here all properties used to be optional to allow the request to only submit the properties whose values change.
To enable the use of polymorphism here as well I need to make the scale_type (discriminator) required to know what type the user wants to patch, is this the accepted way?
Or should we do smarter validation and deserialization on the service to keep everything optional as well.
 
@johanste response

This is the prevailing guidance in this scenario has been:
 
Discriminator/kind is not required – and in fact, usually not allowed to change. This is the default answer.
If you do allow for change of kind, it is indeed service specific, and only properties that map 1:1 between the old and new kind/type are migrated. You may fail the request with a 409 response if one or more properties of the existing resource cannot be migrated to the new kind. The principle of least surprise is applied on a case-by-case basis. If you are changing to a kind that is effectively a superset of the existing kind, this can make sense.
If you do not allow for kind, and you get a request to modify properties not available in the current kind, you return 409 Conflict indicating that the resource cannot be updated like this.
 
… but as always, feedback is welcome…
 
On a side note, this problem exists whenever you have interdependency between property values in a resource. Discriminated polymorphic types is one instance where this happens. A common other case is that only certain SKUs of a resource allow for specific configurations to be set.

**Comment by markweitzel** [comment]
#332 is related to this. I'm closing this one and we will use #331  one as the main issue driving this area of work.
