### ISSUE TITLE
Learning Together

### ISSUE THREAD

**Issue by Sub69Beach69Sup** [Microsoft/api-guidelines#360]

**Comment by Sub69Beach69Sup** [comment]
I want to start with some common ground and attempt to learn as a team. I am not sure whether I have any help or if I am in this alone. But I think I will give it a shot and see what happens. I am limited in what I am able to do because I don't have access to a computer or laptop all of my work is currently restricted to my phone and my phone has been hacked since I got it. So that being said input and contributions are welcome please not your activity and be detailed with your descriptions. Thank you and I look forward to hearing back from you soon and working with you on this project for the next few weeks. 
                         Sincerely,
                                 Beachem

**Comment by gareth-a-jones** [comment]
This appears to be spa,.
