### ISSUE TITLE
Add naming guidance to Azure API Guidelines

### ISSUE THREAD

**Issue by mikekistler** [Microsoft/api-guidelines#368]
Add guidance for naming of properties, parameters, etc to the Azure API Guidelines.

We can probably borrow some of the guidance the MS Graph team has written:

https://github.com/microsoft/api-guidelines/blob/vNext/graph/GuidelinesGraph.md#naming

**Comment by heaths** [comment]
A few common ones come to mind re: dates e.g.,

* `createdOn`
* `updatedOn`
* `notBefore`
* `expiresOn` (often `notAfter`)
* `confidence`/`confidenceThreshold` (drop "Score")

Some of these were discussed at length early on for our first track 2 GAs like Key Vault, but I think over time have been forgotten. Better to bake that into the swagger development process - or at least into the code gen / SDK review process.

**Comment by JeffreyRichter** [comment]
For Boolean naming, I like the guidance [here](https://pike96.com/posts/boolean-naming-conventions/)

**Comment by mikekistler** [comment]
This was addressed by #391
