### ISSUE TITLE
Example Reference Implementations

### ISSUE THREAD

**Issue by RehanSaeed** [Microsoft/api-guidelines#38]
I'm interested in seeing a working example or reference implementation following these guidelines. A code sample tells a 1000 words. As these guidelines are supposed to be generic perhaps a code sample could be written in a few different popular languages.

Personally, I'm interested in seeing a working sample written in ASP.NET Core. There is no OData support in ASP.NET Core, so I'm particularly interested in a generic solution for sorting, filtering, searching, including/excluding properties.

**Comment by dodekeract** [comment]
While this sounds like a good idea, I think it's outside of the scope of this project.

**Comment by cleemullins** [comment]
This would be great. 

Unfortunately, I haven't found any volunteers yet.

**Comment by garethj-msft** [comment]
Agreed this would be good, but it feels like it would belong in a different repo referencing this one.
