### ISSUE TITLE
Link to Breaking Changes policy is inaccessible

### ISSUE THREAD

**Issue by DominikMe** [Microsoft/api-guidelines#384]
The Azure guidelines refer to http://aka.ms/AzBreakingChangesPolicy/ which shows as a broken link
<img width="326" alt="image" src="https://user-images.githubusercontent.com/1885005/183771727-bdbfd1e1-77be-42df-9da5-84ff93a4a20d.png">

Please consider either making the Breaking Changes policy a public document, or give read access permissions to all Microsoft employees.

**Comment by markweitzel** [comment]
Fixed
