### ISSUE TITLE
Conflicting guidance in Azure guidelines on ODATA query parameters names

### ISSUE THREAD

**Issue by forteddyt** [Microsoft/api-guidelines#385]
In https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#query-options, it states
> ⛔ DO NOT prefix any of these query parameter names with "$" (the convention in the [OData standard](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_QueryingCollections)).

However in other Azure API guidelines (such as https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md) there is consistent examples of these ODATA query parameters being defined with a leading `$`.

Which is correct? Do I define my ODATA query parameters with a leading `$` or not?

**Comment by JeffreyRichter** [comment]
The first link is for Azure data-plane services. The second link is for RPs. We're working on aligning these more as time goes on and I suspect that RPs would adopt the removal of the $. Whether you can do this now or now for an RP is up to the members of the ARM team; you'll need to contact them.
