### ISSUE TITLE
Main guidelines should say that $expand is a should have

### ISSUE THREAD

**Issue by dkershaw10** [Microsoft/api-guidelines#414]
See https://github.com/microsoft/api-guidelines/blob/vNext/graph/GuidelinesGraph.md#query-support
This doesn't mention $expand at all

IMHO this should be a "should have" for navigation properties.  We *could* qualify further with:

- `GET collection/{id}?$expand=navProp1` is "should have", and
- `GET collection?$expand=navProp1` is "nice to have" (as this is more computationally expensive for some API producers, so they don't want to support it.

**Comment by OlgaPodo** [comment]
updated
