### ISSUE TITLE
Hyphens or underscores in URLs?

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/api-guidelines#47]
Currently there is no guidance in the guidelines whether hyphens or underscore are preferred to connect words within a URL component.
Is that because you are undecided or do you explicitly not want to make a recommendation?

**Comment by cleemullins** [comment]
This is a case of us trying not to break into Jail. :)

**Comment by johngossman** [comment]
We just remain silent on things unless there is a strong consensus or a strong need for consistency
