### ISSUE TITLE
Rethink some concepts having the existing jsonapi

### ISSUE THREAD

**Issue by kkamkou** [Microsoft/api-guidelines#50]
I liked this repository just with one reason, somebody decided to create more or less readable guideline, which I can recommend to others(besides the using it myself). In the same time, we have http://jsonapi.org/, which is working and stable specification. And very reliable.

Here, I would like to suggest you to review it and merge if possible. Otherwise, most of guidelines are covered by "Restful web apis" book. To have one more interpretation of the output format is not really a contribution, in this case it produces destructful effect rather than positive.

Nevertheless, thank you for the engagement.

**Comment by garethj-msft** [comment]
Thanks for the feedback kkamkou.  The guidelines represent Microsoft's actual practices in building our APIs at present, and right now, we're not using jsonapi.  It is an  interesting general purpose format that we might take more of a look at in future, but for now we would not want to merge it into our guidelines.
