### ISSUE TITLE
The definition of JSON has changed refer to RFC7159

### ISSUE THREAD

**Issue by kuitos** [Microsoft/api-guidelines#54]
The definition of JSON has changed.
see [RFC7159](https://tools.ietf.org/html/rfc7159)

> 2.  JSON Grammar

>   A JSON text is a sequence of tokens.  The set of tokens includes six
>   structural characters, strings, numbers, and three literal names.

>   A JSON text is a serialized value.  Note that certain previous
>   specifications of JSON constrained a JSON text to be an object or an
>   array.  Implementations that generate only objects or arrays where a
>   JSON text is called for will be interoperable in the sense that all
>   implementations will accept these as conforming JSON texts.

>      JSON-text = ws value ws

any ideas to adapt to this?

**Comment by cleemullins** [comment]
I'm not sure what you're asking. I'll re-read the RFC as it looks interesting.

**Comment by darrelmiller** [comment]
@cleemullins RFC7159 acknowledged the change that was made in ECMA's definition of JSON that a JSON value on it's own can be at the root of a JSON document.  Earlier versions of IETF specs used to say only arrays or objects could be at the root.

Be warned also, the IETF spec is about to be updated again... https://tools.ietf.org/html/draft-ietf-jsonbis-rfc7159bis-02  I believe that this is just another sync with that has changed in the ECMA version.

**Comment by garethj-msft** [comment]
I think that one thing we should probably clarify (somewhere better than this comment) is that we really are not looking in this core repo to adapt the guidelines to the on a fast moving basis other than to make additive change for things that are missing or correct things that are erroneous.  For this to serve as Microsoft's guidelines for API consistency, we need some stability to form a baseline for teams to target.   We'd encourage forks to go along and evolve at a more rapid pace..  When a head of industry change, good ideas in forks and internal learning has built up, we'll take non-additive, non-corrective change. 

An example here is that today we'd typically return a single value wrapped in an object (borrowing from OData), whereas now per RFC7159 we don't really need to.  But for a while at least its better to be consistent across our services.

**Comment by kuitos** [comment]
@garethj-msft Thanks for your explanation and I agree with your opinion.
I think you can also explain this in the guideline to avoid anybody else confused.
