### ISSUE TITLE
Versioning via headers?

### ISSUE THREAD

**Issue by mj1856** [Microsoft/api-guidelines#58]
[Section 12.1 - Versioning Formats](https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#121-versioning-formats) only discusses passing a version on the URL, either in the path or in the querystring.

It is also very common to pass an API version via HTTP headers instead, either via custom headers, or as part of `Accept` and `Content-Type` headers (aka, Media Type Versioning).  These are both described in [this guidance](https://azure.microsoft.com/en-us/documentation/articles/best-practices-api-design/#versioning-a-restful-web-api).

IMHO, these approaches should be mentioned, whether acceptable or unacceptable.  Currently, there is no mention of them.

**Comment by cleemullins** [comment]
We had them in for a while, and ended up removing them. After talking with a number of internal teams, we consider the API-In-A-Header to have caused many problems, and actively discourage it's use. 

I could be persuaded to put that back in, but in general we kept the guidance "Do this", rather than "Don't do that".

**Comment by darrelmiller** [comment]
There is a big difference between versioning in a custom header and versioning the payload using a versioned media type identifier.  Versioning resource interactions using a custom header is full of disadvantages and I would personally never recommend that.

However, attaching a version number to a media type identifier is not a whole lot different to putting a version number in the payload itself, as HTML, XML and many other formats have done for years.  Media type versioning has the added feature of being able to conneg versions, which has some value, but I believe is overrated in its utility.

As another point of reference, the upcoming version of OpenApi (fka Swagger) will be using a media type that optionally allows you to specify a media type parameters.  e.g application/openapi+json;version=2.0

**Comment by cecilphillip** [comment]
If you don't mind, what are some of these issues exactly? Maybe having a "don't use headers for versioning" section might be helpful

**Comment by garethj-msft** [comment]
As Chris says, we generally try to minimize the negative guidance as opposed to the positive in this document.   Header-based versioning (outwith media type versioning) is problematic for a few reasons - it's harder for consumers to store what version they called, proxies and forwarders can easily lose the custom headers.  But be aware that this is all a contentious issue and other opinions are very much available.  This is just our take on it.

**Comment by EralpB** [comment]
I would support Media Type Versioning, it should be the future, especially for those in-company APIs, but if you are aiming the public developer audience.. it might be a good idea to use URL versioning since it is easier.
One thing is for sure, just forget about custom header fields :)

**Comment by gareth-a-jones** [comment]
I think our position here is fairly clear.
