### ISSUE TITLE
References to RFC2616 should probably be switched to RFC 7231 or RFC 7230

### ISSUE THREAD

**Issue by darrelmiller** [Microsoft/api-guidelines#6]
RFC 2616 was been replaced by RFC 7230,7231,7232,7233,7334 and 7235 two years ago and is a more consistent, accurate and clearer description of HTTP.  Most of the core semantics of HTTP are described in 7231 and would be a better reference than pointing to RFC 2616

**Comment by RobDolinMS** [comment]
Thanks for the suggestion @darrelmiller.  Would you want to submit as a pull request?

**Comment by darrelmiller** [comment]
Sure, I can do that.

**Comment by gregpardo** [comment]
Issue #12 is a duplicate of this I believe

**Comment by cleemullins** [comment]
The PR for this has been merged. Thanks @darrelmiller !
