### ISSUE TITLE
Naming guidelines are needed

### ISSUE THREAD

**Issue by garethj-msft** [Microsoft/api-guidelines#62]
The document is missing detailed guidelines on how to name resources, types in metadata documents, headers etc.

**Comment by dodekeract** [comment]
Are you referring to specific names like "always call X Y" or rules of thumb, like "as short, but precise as possible"?

**Comment by garethj-msft** [comment]
PR #63 is what we believe is needed for our teams.  That has both your categories in a fairly prescriptive stance.

**Comment by garethj-msft** [comment]
Added to vNext branch
