### ISSUE TITLE
Response format of single entity

### ISSUE THREAD

**Issue by scriby** [Microsoft/api-guidelines#68]
When returning a collection, the format looks like `{ value: [ ... ], ... }`. When returning a single entity, it's not made clear whether it should also be returned as `{ value: { ... } }` or just `{ ... }`.

Some of the examples hint at returning `{ ... }` directly, but it's not explicitly stated.

**Comment by garethj-msft** [comment]
The expectation is definitely that it is just {}, with no value.    We've not found that the kind of annotations that the value envelope allows have proven useful for single entities.  (nextlink or count are the primary examples).

Be very happy to get a PR making it more explicit.

**Comment by codepunkt** [comment]
How should the request be formatted when a collection is returned not returned as an array, but as a JSON object - e.g.:

```json
{
  "5323f46c-13d1-11e7-93ae-92361f002671": { "name": "item1" },
  "5323f82c-13d1-11e7-93ae-92361f002671": { "name": "item2" }
}
```

vs.

```json
{
  "value": {
    "5323f46c-13d1-11e7-93ae-92361f002671": { "name": "item1" },
    "5323f82c-13d1-11e7-93ae-92361f002671": { "name": "item2" }
  }
}
```

**Comment by gareth-a-jones** [comment]
I would day that isn' a collection, but rather a dictionary, so you can add the metadata to the top-level object adequately, thus not needing the value term.

**Comment by codepunkt** [comment]
When you would normally deal with a collection, you often deal with a dictionary instead. It's used as a collection and iterated over and has the form of a dictionary only for the purpose of faster id lookups.

When you put metadata next to the ids, iteration will be hard if not impossible because you have to exclude all metadata-keys or duck-type on the values.

**Comment by gareth-a-jones** [comment]
OK, sounds like you just answered your own question ;-)
