### ISSUE TITLE
Section 7.4 Supported Verbs should really be Supported Methods

### ISSUE THREAD

**Issue by darrelmiller** [Microsoft/api-guidelines#7]
Although it is common practice to use the phrase HTTP verb, it is inconsistent with the [HTTP specification](https://tools.ietf.org/html/rfc7231#section-4.3), the [.net framework](https://msdn.microsoft.com/en-us/library/system.net.http.httpmethod%28v=vs.118%29.aspx?f=255&MSPPError=-2147217396) and the [IANA Method Registry](https://www.iana.org/assignments/http-methods/http-methods.xml). 

Although most experienced developers will know that verb and method is synonymous in the case of HTTP, this introduces a potential for confusion for new developers.

**Comment by cleemullins** [comment]
Up for writing the PR?

**Comment by darrelmiller** [comment]
@cleemullins Sure.  I'm going to finish the 2616->723x PR first.  That's taking a bit longer than I thought because there were a few things I need to research around the reference to header values.

**Comment by cleemullins** [comment]
The PR for this has been merged.
