### ISSUE TITLE
Clarification on $top / $skip

### ISSUE THREAD

**Issue by scriby** [Microsoft/api-guidelines#70]
I wanted to ask about the meaning of this note:

```
Note: If the server can't honor $top and/or $skip, the server MUST return an error to the client informing about it instead of just ignoring the query options. This will avoid the risk of the client making assumptions about the data returned.
```

Does this mean if a client asks for the top 5 items and there's only 4, that the API should error instead of returning the 4 items?

As a caller who doesn't know the number of items in a collection, I may want to receive at most 20 items, but I don't want the call to completely fail if there weren't 20 items available.

Producing an error when going out of bounds on skip isn't unreasonable. But from the caller's perspective, having the server return an empty array when you've skipped out of bounds is typically the most natural result to deal with (it doesn't require any extra code to handle the edge case).

I'm not sure which assumptions we're trying to guard the callers against making. If the response doesn't include a `@nextLink`, they're getting everything that's available that meets the request. If it does include a `@nextLink`, there's more.

**Comment by RobDolinMS** [comment]
I believe returning 4 items if there are only four available is appropriate.

I suspect the intent is that if the server does not support the `$top` and/or `$skip` querystring parameters, it should not just ignore these.

CC @garethj-msft for his two cents

**Comment by garethj-msft** [comment]
Agreed - th e intent was to return an error if the server does not support top or skip, not in the case of too little data.

**Comment by scriby** [comment]
Thanks, that makes sense.
