### ISSUE TITLE
Many parts of the guidelines are in all caps

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/api-guidelines#8]
I'm aware of [RFC2119](https://www.ietf.org/rfc/rfc2119.txt) which recommends to capitalize certain key words but was wondering if there's also a reason to all capitalize for example headings and the table of contents?

If there is no greater reason, I would vote to either Title case or Start Case the guidelines to increase readability and make them more friendly to the eyes of the reader.

**Comment by johnnliu** [comment]
I read the guideline again after seeing this issue and I'm inclined to agree.

- The table of contents itself is inconsistent with casing.
- All caps has actual meanings in the actual guideline both as technical words: e.g. REST, RESTful, HTTPS, OPTIONS
- And as part of the requirements language https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#43-requirements-language "MUST, SHOULD, SHOULD NOT"

So the liberal use of all capital case in headings distracts from the use in the rest of the text.  In fact, it is much hard to see "SHOULD, SHOULD NOT" with all the headings capitalized and that's when I feel the issue has crossed the line from trivial to important.

Please consider dropping all caps in the headings.

**Comment by RobDolinMS** [comment]
Thanks for the suggestions @lumaxis and @johnnliu.  
I believe this is just a remnant from when we converted the guidelines into Markdown.
Anyone wanting to submit a pull request to fix these from ALL CAPS would be appreciated.

**Comment by cleemullins** [comment]
@BasThomas PR, found [here,](https://github.com/Microsoft/api-guidelines/pull/26) addresses most of this. 

As soon as I get get another set of eyes on it, I'll merge it in. #26
