### ISSUE TITLE
Question about section 9.3.1 nested collections and properties

### ISSUE THREAD

**Issue by a-k-g** [Microsoft/api-guidelines#80]
This is the example in the current guidelines:
```http
GET https://api.contoso.com/v1.0/people/123/addresses
```

```json
{
  "value": [
    { "street": "1st Avenue", "city": "Seattle" },
    { "street": "124th Ave NE", "city": "Redmond" }
  ]
}
```

Now let's say I need to have an API which returns a collection of <person, addresses> for all the people.

Assuming that I have only 2 people "100" and "101", the sample response would be:
```json
[
  {
    "id": "100",
    "value": [
      { "street": "Lombard Street", "city": "San Francisco" }
    ]
  },
  {
    "id": "101",
    "value": [
      { "street": "1st Avenue", "city": "Seattle" },
      { "street": "124th Ave NE", "city": "Redmond" }
    ]
  }
]
```

What should the url for this be?

**Comment by sebadiaz** [comment]
I suggest 

GET https://api.contoso.com/v1.0/people/addresses

or 

GET https://api.contoso.com/v1.0/people/@all/addresses

**Comment by gareth-a-jones** [comment]
In general, we'd try to avoid a separate API, but rather use a $expand parameter on the simple `people `endpoint instead.

So the URL would be 
`GET https://api.contoso.com/v1.0/people?$expand=addresses&$select=id`
which would return a response something like this
```
{
  "value": [
  {
    "id": "100",
    "addresses": [
      { "street": "Lombard Street", "city": "San Francisco" }
    ]
  },
  {
    "id": "101",
    "addresses": [
      { "street": "1st Avenue", "city": "Seattle" },
      { "street": "124th Ave NE", "city": "Redmond" }
    ]
  }
]
}
```

In general, we'd only use the `value `property name as the top level collection container, not below, as there is always a semantically more meaningful name below.
