### ISSUE TITLE
Question about 8.2 : What is "dynamic canary"

### ISSUE THREAD

**Issue by dmytro-y-dev** [Microsoft/api-guidelines#87]
It is mentioned security technique called "dynamic canary" (in section https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#82-service-guidance). I can't find information about it. May someone provide a link with information or explain what is it?

**Comment by jmealo** [comment]
@metamaker: https://msdn.microsoft.com/en-us/library/office/gg552614(v=office.14).aspx

**Comment by dmytro-y-dev** [comment]
@jmealo thanks for link. How it differs from X-XSRF-TOKEN?

**Comment by jmealo** [comment]
@metamaker: I'm not sure, just some in-house terminology. I suppose they used to have a non-dynamic canary? This is a more comprehensive list of security guidelines: https://www.owasp.org/index.php/REST_Security_Cheat_Sheet
