### ISSUE TITLE
OPTIONS must be idempotent

### ISSUE THREAD

**Issue by choudeshell** [Microsoft/api-guidelines#9]
Per RFC 7231, OPTIONS is defined as a safe method. RFC 7231 also states all safe methods are idempotent, hence OPTIONS must be idempotent.

**Comment by manoj-agarwal** [comment]
I agree: https://github.com/Microsoft/api-guidelines/pull/20

**Comment by RobDolinMS** [comment]
Closing as this is fixed in #20.
Thanks @choudeshell for reporting and thanks @manoj-agarwal for preparing the PR.
