### ISSUE TITLE
Suggestion: Machine readable version

### ISSUE THREAD

**Issue by jmealo** [Microsoft/api-guidelines#90]
Are there any plans to provide a machine readable version of these guidelines so that it's possible to auto generate compliance tests (or possibly documentation/client code)?

**Comment by gareth-a-jones** [comment]
No plans.  Are you aware of a machine readable format suitable for capturing this type of guidance?

**Comment by gareth-a-jones** [comment]
Don't think we're seeing anyone come forward with a proposal here, so closing.
