### ISSUE TITLE
Question about 8.2: Why query parameters, not Authorization header?

### ISSUE THREAD

**Issue by oneturkmen** [Microsoft/api-guidelines#91]
It is written that:

*For GET and HEAD calls, avoid requiring request headers that **are not part of the simple set above**. Allow them to be provided as query parameters instead. **The Authorization header is not part of the simple set, so the authentication token MUST be sent through the "access_token" query parameter instead, for resources requiring authentication.***

As I understood, I MUST use the query parameters as a way to send access tokens. The question is: how are you going to get and validate your token, e.g. in Node JS using JWT, via query parameters? Isn't it much more secure and simpler to rather use **Authorization** header, than query parameters?

I may have missed something, hence this question may sound dumb.

PS. Or, is it related only to *CORS preflight requests?*

Thanks anyway!

**Comment by gareth-a-jones** [comment]
Thanks for the spot.  I think this is just a simple omission - care to submit a PR?

**Comment by oneturkmen** [comment]
@garethj-msft Sure, I can do PR. However, can you please elaborate more on the issue?

**Comment by gareth-a-jones** [comment]
I was just suggesting to add Authorization header to the simple standard set.

**Comment by RobDolinMS** [comment]
Closing this issue since we now have a proposed PR in #93
