### ISSUE TITLE
Grouping this repository

### ISSUE THREAD

**Issue by ghost** [Microsoft/api-guidelines#95]
This repository should be in a ASP.NET repository group.

**Comment by darrelmiller** [comment]
Thanks for your suggestion.  However, these guidelines are applicable to HTTP APIs built using many different technology stacks and therefore are not limited to ASP.NET

**Comment by RobDolinMS** [comment]
I agree with @darrelmiller.  These are not just limited to use in ASP.NET.

**Comment by ghost** [comment]
I agree, however I meant as a sub repository under ASP.NET with tags to other areas as well...

**Comment by gareth-a-jones** [comment]
I'd go so far as to say not even all that closely coupled to ASP.Net.  I agree with Rob and Darrel.  Rooting this under a specific technology, even linked to other technologies would send the wrong message that a specific technology is more important than any other in building web APIs.
